### ISSUE TITLE
Нет тегов в окне

### ISSUE THREAD

**Issue by ErToptaev** [dmiandr/context#2]
тегов заполнено определенное количество(не считано)  - но в окне параметры нет ничего подобного  этому https://github.com/dmiandr/context/blob/master/docs/img/tagscloud.png

так  https://cont.ws/uploads/messages/9b/03/d6/c5/bf76a7922fb4886506d4c835.jpg
Это происходит в cont.ws.
ЖЖ не проверял.
браузер Chrome Версия 122.0.6261.129 (Официальная сборка), (64 бит)

**Comment by SMelnik474** [comment]
проверьте  в Эдж

**Comment by SMelnik474** [comment]
> браузер Chrome

проверьте  в Эдж - сейчас было большое обновление.

**Comment by ErToptaev** [comment]
Закрывайте, я всё понял. https://cont.ws/uploads/messages/06/c5/a5/99/66023e09945219a6f49c142b.jpg
